import type { Metadata } from "next";
import monofontoFont from 'next/font/local';
import "./globals.css";

const monofontoRegular = monofontoFont({
  src: '../public/monofonto.ttf',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={monofontoRegular.className}
      >
        {children}
      </body>
    </html>
  );
}
